// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
    production: true,
    productName: 'Dynamic Dashboard Framework',
    productVersion: '0.0.4',
    version: env.npm_package_version,
    menu: {
        documentation: false,
        ai: false,
        notification: false
    },
    boardConfiguration: {
        board: true,
        ai: false,
        endpoint: true
    },
    serverUrl: '',
    apiUrl: 'http://localhost:3000',
    defaultLanguage: 'en-US',
    supportedLanguages: [
        'en-US',
        'fr-FR'
    ]
};
